export const artistSearchStart = 'ARTIST_SEARCH_START'
export const artistSearchSuccess = 'ARTIST_SEARCH_SUCCESS'
export const artistSearchFailure = 'ARTIST_SEARCH_FAILURE'
export const artistGetDataSuccess = 'ARTIST_GET_DATA_SUCCESS'
export const artistGetDataFailure = 'ARTIST_GET_DATA_FAILURE'
